#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
pnpm check-format ||
(
   echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
   false;
)

# Check ESLint Standards
pnpm check-lint ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check tsconfig standards
pnpm check-types ||
(
    echo 'TypeScript Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me...'
echo '👷👷👷👷... Trying to build now'

# Build
pnpm build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

